### ISSUE TITLE
Implement image export from video (Library 2)

### ISSUE THREAD

**Issue by Freeze-FF** [amosproj/amos2023ws03-gui-frame-diff#111]
## User story
1. As a user
2. I want / need a function that can extract images from a video. 
3. So that I can use the compressed video file and extract and save the images. 

## Acceptance criteria
* Find a way to transfer data from Library 2 to Library 3 
* Given a video file generated by Library 2 the function can hand it over to Library 3. 
* This video file or series of images should then be used for further processing and analysis in the ui (Library 3). 

## Definition of done (DoD)
* Create feature branch
* Implement the functionality
* Opened pull request and assigned reviewer
* If necessary: required changes are implemented
* Delete feature branch
* If necessary: Component Test has been written
* Code review has been completed and code has been merged

## DoD general criteria
* Feature has been fully implemented
* Feature has been merged into the mainline
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Developers agreed to release

**Comment by lukas-monet** [comment]
Sounds good! So did we agree that we are working with video files in the ui or will we split it into pictures later?

**Comment by simonsasse** [comment]
most probable the GUI will read a video file using ffmpeg and then display the individual frames.

**Comment by simonsasse** [comment]
closed by #135
