### ISSUE TITLE
Build a frame navigation interface (Library 3)

### ISSUE THREAD

**Issue by Freeze-FF** [amosproj/amos2023ws03-gui-frame-diff#118]
## User story
1. As a developer
2. I want / need an API 
3. So that Library 3 can use functionality of Library 2. 

## Acceptance criteria
* It should be implemented as an abstract class or interface
* Jump n frames forward or backward 
* Jump to a specified percentage of the diff video 
* Jump to a concretely specified frame 
* Jump to the next diff at a specified position

## Definition of done (DoD)
* Create feature branch
* Implement the functionality
* Opened pull request and assigned reviewer
* If necessary: required changes are implemented
* Delete feature branch
* If necessary: Component Test has been written
* Code review has been completed and code has been merged

## DoD general criteria
* Feature has been fully implemented
* Feature has been merged into the mainline
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Developers agreed to release

**Comment by zino212** [comment]
The interface is for now located inside the GUI. We can discuss this further in the next dev meeting if it is needed.
