### ISSUE TITLE
Setup UI-Tests (Library 3)

### ISSUE THREAD

**Issue by lukas-monet** [amosproj/amos2023ws03-gui-frame-diff#166]
## User story
1. As a user
2. I want that the user interface is tested
3. So that I can make sure everything works

## Acceptance criteria
* a framework for ui tests was selected
* one example UI-Tests is implemented in this framework
* the example test passes green
* the UI-Tests are integrated into the CI-Pipeline

## Definition of done (DoD)
* Create feature branch
* Implement the functionality
* Opened pull request and assigned reviewer
* If necessary: required changes are implemented
* Delete feature branch
* If necessary: Component Test has been written
* Code review has been completed and code has been merged

## DoD general criteria
* Feature has been fully implemented
* Feature has been merged into the mainline
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Developers agreed to release

**Comment by simonsasse** [comment]
https://proandroiddev.com/write-unit-tests-and-ui-tests-in-your-kotlin-multiplatform-app-472c27625b5a

**Comment by simonsasse** [comment]
https://www.kodeco.com/books/kotlin-multiplatform-by-tutorials/v1.0/chapters/8-testing
