### ISSUE TITLE
Manual saving of a frame collage as png

### ISSUE THREAD

**Issue by lukas-monet** [amosproj/amos2023ws03-gui-frame-diff#167]
## User story
1. As a user
2. I want to save Video 1, Video 2 and Difference in one colllage
3. So that I can get a analyze the difference between the three frames

## Acceptance criteria
* add menu list to video player screen
* there should be button with the text "export frame collage"

![Image](https://github.com/amosproj/amos2023ws03-gui-frame-diff/assets/112629761/d59fc76a-53db-4433-9aef-1ce297da0cdc)

* when clicking the button a frame collage of the current selected frames should be created
* there should be option to choose the location where the file is stored in the file explorer
* the frame collage should look like this: 

one the left side video 1, in the middle difference video and on the right side video 2
![Image](https://github.com/amosproj/amos2023ws03-gui-frame-diff/assets/112629761/bd6d3772-5907-4588-b5b1-0421ef1784f1)

## Definition of done (DoD)
* Create feature branch
* Implement the functionality
* Opened pull request and assigned reviewer
* If necessary: required changes are implemented
* Delete feature branch
* If necessary: Component Test has been written
* Code review has been completed and code has been merged

## DoD general criteria
* Feature has been fully implemented
* Feature has been merged into the mainline
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Developers agreed to release

**Comment by fs3itz** [comment]
https://developer.android.com/jetpack/compose/components/app-bars
