### ISSUE TITLE
Improvements of the GUI: Improve appearance 

### ISSUE THREAD

**Issue by Freeze-FF** [amosproj/amos2023ws03-gui-frame-diff#171]
## User story
As a user
I want / need an Intuitiv and understandable GUI
So that I can do the tasks easily and fastly.  

## Acceptance criteria
* Windows: the file selection explorer should be a normal optimized explorer with a moder look e.g.
![image](https://github.com/amosproj/amos2023ws03-gui-frame-diff/assets/96525491/400700de-52d1-475f-8f45-4c1eca309c39)

The window should contain the the program name and version in the top window frame, e.g.
image
* The window should contain the the program name and version in the top window frame, e.g. 
![image](https://github.com/amosproj/amos2023ws03-gui-frame-diff/assets/96525491/243616be-3db1-47fb-a68f-4f8b5268dd87)

## Definition of done (DoD)
* Create feature branch
* Implement the functionality
* Opened pull request and assigned reviewer
* If necessary: required changes are implemented
* Delete feature branch
* If necessary: Component Test has been written
* Code review has been completed and code has been merged

## DoD general criteria
* Feature has been fully implemented
* Feature has been merged into the mainline
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Developers agreed to release

**Comment by fs3itz** [comment]
https://github.com/Wavesonics/compose-multiplatform-file-picker
