### ISSUE TITLE
Add a short documentation of the algorithm 

### ISSUE THREAD

**Issue by Freeze-FF** [amosproj/amos2023ws03-gui-frame-diff#173]
## User story
1. As a user/ developer
2. I want / need a short documentation of the algorithm that computes the image difference 
3. So that I understand the used algorithm and the idea of the implementation. 

## Acceptance criteria
* It documents and provides an overview about the main functionality of the algorithm 
* All algorithms are named 
* A diagram and then a short explanations of how the algorithm works
* the documentation should be in the github wiki in the design documentation
* Goal: So that it is documented and the user/developer etc. gets an overview and understands the implemented algorithm more quickly 
* E.g. The diagram can be based on that: 
![image](https://github.com/amosproj/amos2023ws03-gui-frame-diff/assets/96525491/58a44c5f-243e-46c9-b328-2b949b7d3be4)

## Definition of done (DoD)
* Create feature branch
* Implement the functionality
* Opened pull request and assigned reviewer
* If necessary: required changes are implemented
* Delete feature branch
* If necessary: Component Test has been written
* Code review has been completed and code has been merged

## DoD general criteria
* Feature has been fully implemented
* Feature has been merged into the mainline
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Developers agreed to release

**Comment by simonsasse** [comment]
So I published a first version, it is definitely not brief but I couldn't help it. These algorithm are too complex to describe them briefly so that the reader understands what's happening.

https://github.com/amosproj/amos2023ws03-gui-frame-diff/wiki/Design-Documentation#differencegenerator-library
