### ISSUE TITLE
Remember last opened folder in file picker (Library 3)

### ISSUE THREAD

**Issue by lukas-monet** [amosproj/amos2023ws03-gui-frame-diff#189]
## User story
1. As a user
2. I want that every file picker remembers the last opened location
3. So that I do not have to click everytime through all folders

## Acceptance criteria
* when the file picker is opened the last opened folder should be present not the home folder
* every file picker should remember it's own last opened folder (for instance video 1 and video2 file picker should remember it's own path)
* when the file picker is opened the first time (new program start) it should show the home folder

## Definition of done (DoD)
* Create feature branch
* Implement the functionality
* Opened pull request and assigned reviewer
* If necessary: required changes are implemented
* Delete feature branch
* If necessary: Component Test has been written
* Code review has been completed and code has been merged

## DoD general criteria
* Feature has been fully implemented
* Feature has been merged into the mainline
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Developers agreed to release

**Comment by simonsasse** [comment]
I'll wait for #199 to be merged or almost finished. This ticket here is so small and the work will most likely be for nothing if I do on top of the current main.
