### ISSUE TITLE
Change to reference and current video 

### ISSUE THREAD

**Issue by Freeze-FF** [amosproj/amos2023ws03-gui-frame-diff#205]
## User story
1. As a user
2. I want / need an application that can manage a reference and current video
3. So that I get a better overview of the two videos 

## Acceptance criteria
* The system should encode the creation date into the metadata of the generated video. This could be in the form of a Unix timestamp.
* At any given time, the user should be aware of which videos are being compared. This could be achieved by using metadata.
* The system should warn the user when they are about to compare two videos (e.g., “You are comparing Video 1 (=reference video), which is newer, and Video 2 (=current video), which is older, are you sure you want to do this?”).
* The warning should be shown when pressing "Compute and Display Differences"
* The user has the option to skip the warning and continue
* The system should be flexible enough to handle video sequences that were not generated from Library 1 (in this case use created_at of the file as fallback)
* The system should have the capability to archive videos with a timestamp (Library 1)
* When Library 1 is generating a video a timestamp should be set
* see comment

## Definition of done (DoD)
* Create feature branch
* Implement the functionality
* Opened pull request and assigned reviewer
* If necessary: required changes are implemented
* Delete feature branch
* If necessary: Component Test has been written
* Code review has been completed and code has been merged

## DoD general criteria
* Feature has been fully implemented
* Feature has been merged into the mainline
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Developers agreed to release

**Comment by lukas-monet** [comment]
Da es bei .mov nicht möglich ist Metadaten anzuhängen, würde ich vorschlagen wir implementieren die Lösung mit einem Timestamp der gesetzt wird von Library 1 nur bei .mkv Videos. Bei .mov Videos greifen wir dann auf den Fallback zurück und verwenden einfach das Erstellungsdatum des Videos.
