### ISSUE TITLE
Improve design with Material 3

### ISSUE THREAD

**Issue by lukas-monet** [amosproj/amos2023ws03-gui-frame-diff#235]
## User story
1. As a user
2. I want a nice UI
3. So that I can use the software easily

## Acceptance criteria
* upfront the meeting: 
* adjust colors that they are readable 
* text overflows in buttons should be fixed
* fix the displaying of the statistical information
* there should be a 2h meeting together with the PO's to finish the final UI 
* the UI should be reviewed by minimum 3 people

## Definition of done (DoD)
* Create feature branch
* Implement the functionality
* Opened pull request and assigned reviewer
* If necessary: required changes are implemented
* Delete feature branch
* If necessary: Component Test has been written
* Code review has been completed and code has been merged

## DoD general criteria
* Feature has been fully implemented
* Feature has been merged into the mainline
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Developers agreed to release

**Comment by zino212** [comment]
See [PR](https://github.com/amosproj/amos2023ws03-gui-frame-diff/pull/251) for progress and checklist
