### ISSUE TITLE
Adjust Input of Library 1

### ISSUE THREAD

**Issue by lukas-monet** [amosproj/amos2023ws03-gui-frame-diff#25]
## User story
1. As a user of Library 1
2. I want to include Library 1 into my Android Kotlin project
3. So that I can hand over image by image to reduce the size

## Acceptance criteria
* It is possible to add image by image encapsulated in a interface 
* It is possible to hand over image by image to a instance of the video accumulator (Library 1)
* the interface is  encapsulated in such way that its possible to call Library 1 from another Android Kotlin App (it should be possible to create a instance of Video Accumulator and add image by image)
* for demo purposes we need have the option to read images from file system
* The image datatype should be following:
          from filesystem: start with PNG
          input parameter in the interface: Kotlin datatype that represents Image

**Comment by akriese** [comment]
Closing this as the duplicate (#26) is being used in our feature board
