### ISSUE TITLE
differentiate between added or deleted frames and changes within the frame (Library 2)

### ISSUE THREAD

**Issue by lukas-monet** [amosproj/amos2023ws03-gui-frame-diff#47]
## User story
1. As a user
2. I want to see if there are changes within a certain frame
3. So that I can analyze the differences between the two videos

## Acceptance criteria
* it exists a algorithm that can differentiate if a frame of video b is added or deleted in comparison to video a or if there is a difference within the frame (for instance the text of the button changed within the frame)
* it should be possible to compute the exact location of the difference within the frame
* This question is answered and implemented accordingly: How do you decide whether there are simple pixel differences, but in general the same screen OR is it a completely different screen, e.g. because there are some inserted screens? Think how you can distinguish both cases and how to make a good decision!

**Comment by a-miscellaneous** [comment]
functionality is there need more optimization in seperate ticket
