### ISSUE TITLE
Sketch a draft of the GUI and build a skeleton for Library 3 (Library 3)

### ISSUE THREAD

**Issue by Freeze-FF** [amosproj/amos2023ws03-gui-frame-diff#56]
## User story
1. As a user
2. I want to have a good GUI that looks like a video editing tool
3. So that I can effectively and efficiently work with the software. 

This ticket depends on #49.  

## Acceptance criteria
* Sketch a draft of what the final GUI should look like 
* Plan the GUI understandable and intuitive 
* The goal is to create a skeleton that already contains the basic functionality of a video editing tool, e.g. selecting and loading videos, then showing the video

**Comment by zino212** [comment]
![Image](https://github.com/amosproj/amos2023ws03-gui-frame-diff/assets/52202194/95aa5593-035e-40ca-8a1f-24cb19fc6910)



![Image](https://github.com/amosproj/amos2023ws03-gui-frame-diff/assets/52202194/77f09a35-0b85-442b-8c7a-fbce87224dcf)


Sketches for this ticket by @fs3itz , @AlperK61 and me.

**Comment by AlperK61** [comment]
![image](https://github.com/amosproj/amos2023ws03-gui-frame-diff/assets/92909013/6a7fa67a-cf54-412d-acd0-e4e6a8854caa)

**Comment by zino212** [comment]
I don't think that this ticket is already finished, because some functionality is supposed to be part of it.

**Comment by AlperK61** [comment]
I think so, because at the moment it is not possible to create the final version of the GUI. this is an iterarive process and it should be enought to create the first page for now.
