### ISSUE TITLE
Check licenses of all projects

### ISSUE THREAD

**Issue by lukas-monet** [amosproj/amos2023ws03-gui-frame-diff#57]
## User story
1. As a user
2. I want to make sure that are all licenses under open source
3. So that I can reuse the Libraries

## Acceptance criteria
* all dependencies have been checked to confirm with open source governance

![Image](https://github.com/amosproj/amos2023ws03-gui-frame-diff/assets/112629761/f4987401-9f61-48b8-b04e-36c49367dc00)

**Comment by Freeze-FF** [comment]
Industry partner proposed an MIT licence!
