### ISSUE TITLE
Irregular work for Sprint 05

### ISSUE THREAD

**Issue by lukas-monet** [amosproj/amos2023ws03-gui-frame-diff#72]
## Acceptance criteria
* create build process video is done
* name and upload file to sprint-05/build-process-video.mkv

**Comment by zino212** [comment]
The video should show 

1. Cloning the repo
2. Building the project parts
3. Running the tests
4. Running the project parts

see Deliverables Document for the whole Description:
https://docs.google.com/document/d/14xj_KeAx0tCbh7b4SJmDOY8tlpWwSrZO_i_XRDVOtk0/edit#heading=h.xgttzgekcivp

**Comment by zino212** [comment]
Do you already know when you will be doing that? @simonsasse
