### ISSUE TITLE
research and improve compression rate (Library 1)

### ISSUE THREAD

**Issue by lukas-monet** [amosproj/amos2023ws03-gui-frame-diff#89]
## User story
1. As a user
2. I want that the accumulated video needs less storage than all images
3. So that I have less storage consumption on the head unit

## Acceptance criteria
* a test that accumulates 10, 100, 500, 800 and 1000 images to a video is written
* it is documented how the size of the video develops with more and more images (for 10, 100, 500, 800 and 1000 images) 
* final result: the video takes less storage then the single images

## Definition of done (DoD)
* Create feature branch
* Implement the functionality
* Opened pull request and assigned reviewer
* If necessary: required changes are implemented
* Delete feature branch
* If necessary: Component Test has been written
* Code review has been completed and code has been merged

## DoD general criteria
* Feature has been fully implemented
* Feature has been merged into the mainline
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Developers agreed to release

**Comment by simonsasse** [comment]
Research:
http://www.compression.ru/video/codec_comparison/pdf/lossless_codecs_test_en.pdf 
- FFV1 is second best in all cases after MSUlab
- MSUlab codecs are proprietary (https://en.wikipedia.org/wiki/MSU_Lossless_Video_Codec)
