### ISSUE TITLE
Irregular work for Sprint 6

### ISSUE THREAD

**Issue by lukas-monet** [amosproj/amos2023ws03-gui-frame-diff#95]
## Acceptance criteria
* create a documentation, how to use our software (user documentation)
* create a documentation, about the design of our software (architecture, code) (design documentation)
* create a documentation, how to build and deploy our project (build/deploy documentation)
* documents are uploaded to sprint-06/{user|design|build}-documentation.pdf

Hint: If possible, use Github’s facilities for the documentation. The GitHub wiki is best, GitHub pages are fine as well, markdown files too.
If you can’t create PDFs, still create PDFs that provide links to the documentation for viewing.

**Comment by akriese** [comment]
On build and deploy, we can use my write-up for the [build process video](https://github.com/amosproj/amos2023ws03-gui-frame-diff/blob/main/Deliverables/sprint-05/build-process-video-commands.txt)
